force-app/main/default/objects/Aeropuerto__c/Aeropuerto__c.object-meta.xml
<CustomObject>
    <description>Es una locación fisica acondicionado para depachar y recibir todo tipo de vuelos en diferentes ciudades.</description>
    <label>Aeropuerto</label>
    <nameField>
        <label>Nombre de Aeropuerto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aeropuertos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clima__c/Clima__c.object-meta.xml
<CustomObject>
    <description>El clima es el registro de las condicines climáticas para un aeropuertoen un momento determinado. Se guarda 24 horas antes de realizar cada vuelo.</description>
    <label>Clima</label>
    <nameField>
        <displayFormat>CL-{0000}</displayFormat>
        <label>Nombre de Clima</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Climas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Clima__c/fields/Aeropuerto__c.field-meta.xml
<CustomField>
    <fullName>Aeropuerto__c</fullName>
    <label>Aeropuerto</label>
    <referenceTo>Aeropuerto__c</referenceTo>
    <relationshipLabel>Climas</relationshipLabel>
    <relationshipName>Climas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Clima__c/fields/Fecha_y_Hora_Prediccion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_y_Hora_Prediccion__c</fullName>
    <description>Indica el momento exacto en el que fue tomada la temperatura</description>
    <label>Fecha y Hora Prediccion</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Clima__c/fields/Temperatura__c.field-meta.xml
<CustomField>
    <fullName>Temperatura__c</fullName>
    <description>Numero de grados registrados en un momento exacto</description>
    <inlineHelpText>Solo ingresar numeros enteros sin unidad de medida</inlineHelpText>
    <label>Temperatura</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Clima__c/fields/Unidad_de_Medida__c.field-meta.xml
<CustomField>
    <fullName>Unidad_de_Medida__c</fullName>
    <description>Unidad de medida de la toma de temperatura en un aeropuerto dado</description>
    <label>Unidad de Medida</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Centigrados</fullName>
            </value>
            <value>
                <fullName>Farenheit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClimaRest.cls
global with sharing class ClimaRest {
    
    
    global static void getClimas(){
        
        String key = 'cd1c441e329b68884d1b729d57889a22';
        DateTime fechaPartida = System.now().addHours(24);
        DateTime fechaLlegada = System.now().addHours(1);
        DateTime fechaTomada = System.now();
        String unidad = 'Centigrados';
        Decimal temperatura;
        Decimal latitud;
        Decimal longitud;
        String  aeropuerto;
        List<Product2> vuelos  = [SELECT Id, Name, Fecha_y_hora_de_partida__c, Aeropuerto_de_Partida__r.Ubicacion__latitude__s, Aeropuerto_de_Partida__r.Ubicacion__longitude__s,
                                Aeropuerto_de_Llegada__r.Ubicacion__latitude__s, Aeropuerto_de_Llegada__r.Ubicacion__longitude__s 
                                FROM Product2 WHERE Fecha_y_hora_de_partida__c > :fechaTomada];
        List<Clima__c> climas = new List<Clima__c>();
        for (Product2 v : vuelos) {
            if (v.fecha_y_hora_de_partida__c <= fechaPartida) {
                latitud = v.Aeropuerto_de_Partida__r.Ubicacion__latitude__s;
                longitud = v.Aeropuerto_de_Partida__r.Ubicacion__longitude__s;
                aeropuerto = v.Aeropuerto_de_Partida__r.Id;                
            }
            if (v.fecha_y_hora_de_partida__c <= fechaLlegada) {
                latitud = v.Aeropuerto_de_Partida__r.Ubicacion__latitude__s;
                longitud = v.Aeropuerto_de_Partida__r.Ubicacion__longitude__s; 
                aeropuerto = v.Aeropuerto_de_llegada__r.Id;                
            }
            Http http = new Http();
            HttpRequest request = new HttpRequest();
            request.setEndpoint('https://api.openweathermap.org/data/2.5/weather?lat='+latitud+'&lon='+longitud+'&appid='+key+'&units=metric');
            request.setMethod('GET');
            HttpResponse response = http.send(request);
            if (response.getStatusCode() == 200) {
                Map<String, Object> result = (Map<String, Object>)JSON.deserializeUntyped(response.getBody());
                Map<String, Object> temp = (Map<String, Object>) result.get('main');
                temperatura = (decimal)temp.get('temp');
                Clima__c clima = new Clima__c(Aeropuerto__c = Aeropuerto, Temperatura__c = temperatura,
                                            Unidad_de_Medida__c = unidad, Fecha_y_Hora_Prediccion__c = fechaTomada);
                climas.add(clima);
                
                System.debug(latitud);
                System.debug(longitud);
            }              
        }
        Insert climas;
    } 
     
}