force-app/main/default/objects/Aeropuerto__c/Aeropuerto__c.object-meta.xml
<CustomObject>
    <description>Es una locación fisica acondicionado para depachar y recibir todo tipo de vuelos en diferentes ciudades.</description>
    <label>Aeropuerto</label>
    <nameField>
        <label>Nombre de Aeropuerto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aeropuertos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Aeropuerto__c/fields/Ciudad__c.field-meta.xml
<CustomField>
    <fullName>Ciudad__c</fullName>
    <description>Ciudad en la que se encuentra ubicado el aeropuerto</description>
    <label>Ciudad</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Pais__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Albacete</fullName>
            </value>
            <value>
                <fullName>Ámsterdam</fullName>
            </value>
            <value>
                <fullName>Antofagasta</fullName>
            </value>
            <value>
                <fullName>Arica</fullName>
            </value>
            <value>
                <fullName>Astaná</fullName>
            </value>
            <value>
                <fullName>Asunción</fullName>
            </value>
            <value>
                <fullName>Atenas</fullName>
            </value>
            <value>
                <fullName>Bagram</fullName>
            </value>
            <value>
                <fullName>Bahia</fullName>
            </value>
            <value>
                <fullName>Balmaceda</fullName>
            </value>
            <value>
                <fullName>Bamiyán</fullName>
            </value>
            <value>
                <fullName>Barcelona</fullName>
            </value>
            <value>
                <fullName>Basilea, Mulhouse, Friburgo</fullName>
            </value>
            <value>
                <fullName>Beja</fullName>
            </value>
            <value>
                <fullName>Berlín</fullName>
            </value>
            <value>
                <fullName>Bilbao</fullName>
            </value>
            <value>
                <fullName>Bogotá</fullName>
            </value>
            <value>
                <fullName>Budapest</fullName>
            </value>
            <value>
                <fullName>Buenos Aires</fullName>
            </value>
            <value>
                <fullName>Burdeos</fullName>
            </value>
            <value>
                <fullName>Cali</fullName>
            </value>
            <value>
                <fullName>Caracas</fullName>
            </value>
            <value>
                <fullName>Casablanca</fullName>
            </value>
            <value>
                <fullName>Castellon</fullName>
            </value>
            <value>
                <fullName>Cayo Coco</fullName>
            </value>
            <value>
                <fullName>Chicago</fullName>
            </value>
            <value>
                <fullName>Chihuahua</fullName>
            </value>
            <value>
                <fullName>Ciudad de Corrientes</fullName>
            </value>
            <value>
                <fullName>Ciudad de Formosa</fullName>
            </value>
            <value>
                <fullName>Ciudad de Guatemala</fullName>
            </value>
            <value>
                <fullName>Medellín</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Aeropuerto__c/fields/Codigo_IATA__c.field-meta.xml
<CustomField>
    <fullName>Codigo_IATA__c</fullName>
    <description>Muestra el código IATA para cada aeropuerto</description>
    <label>Código IATA</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Avion__c/Avion__c.object-meta.xml
<CustomObject>
    <description>Aeronave que sobrevuela los cielos transportando pasajeros o carga</description>
    <label>Avion</label>
    <nameField>
        <displayFormat>AV-{00000}</displayFormat>
        <label>Número de Avion</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aviones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Avion__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Indica que tipo de avión es, si de pasajeros o carga</description>
    <label>Tipo</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clima__c/Clima__c.object-meta.xml
<CustomObject>
    <description>El clima es el registro de las condicines climáticas para un aeropuertoen un momento determinado. Se guarda 24 horas antes de realizar cada vuelo.</description>
    <label>Clima</label>
    <nameField>
        <displayFormat>CL-{0000}</displayFormat>
        <label>Nombre de Clima</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Climas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Clima__c/fields/Aeropuerto__c.field-meta.xml
<CustomField>
    <fullName>Aeropuerto__c</fullName>
    <label>Aeropuerto</label>
    <referenceTo>Aeropuerto__c</referenceTo>
    <relationshipLabel>Climas</relationshipLabel>
    <relationshipName>Climas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Clima__c/fields/Temperatura__c.field-meta.xml
<CustomField>
    <fullName>Temperatura__c</fullName>
    <description>Numero de grados registrados en un momento exacto</description>
    <inlineHelpText>Solo ingresar numeros enteros sin unidad de medida</inlineHelpText>
    <label>Temperatura</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ClimaRestTest.cls
@isTest
public with sharing class ClimaRestTest {
    
    @TestSetup
    static void makeData(){
        Datetime tiempo = Datetime.now();
        List<Aeropuerto__c> aeropuertos = new List<Aeropuerto__c>();
        aeropuertos.add(new Aeropuerto__c(Name = 'Aeropuerto Internacional José María Cordova', Codigo_IATA__c = 'MDE',
                                        Ciudad__c = 'Medellín', Ubicacion__Latitude__s = 6.2443382,  Ubicacion__Longitude__s = -75.573553));
        aeropuertos.add(new Aeropuerto__c(Name = 'Aeropuerto Internacional El Dorado', Codigo_IATA__c = 'BOG',
                                        Ciudad__c = 'Bogotá', Ubicacion__Latitude__s = 4.6534649,  Ubicacion__Longitude__s = -74.0836453));
        insert aeropuertos;

        Avion__c avion = new Avion__c(Tipo__c = 'Airbus A330');
        insert avion;

        Product2 vuelo = new Product2(Name = 'AE-20005',Aeropuerto_de_partida__c = aeropuertos[0].Id,
                                     Aeropuerto_de_llegada__c= aeropuertos[1].Id, Fecha_y_hora_de_partida__c = tiempo.addMinutes(30),
                                     Fecha_y_hora_estimada_de_llegada__c = tiempo.addHours(2), Avion__c = avion.Id, IsActive = true);
        insert vuelo;
    }


    @isTest
    static void climaPartida(){
        test.startTest();
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('ClimaMock');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json;charset=UTF-8');

        // Associate the callout with a mock response
        Test.setMock(HttpCalloutMock.class, mock);
        // Call method to test
        
        ClimaRest.getClimaPartida();
        test.stopTest();

        List<Clima__c> clima = [SELECT Id FROM clima__c WHERE Temperatura__c = 299.71];

        System.assertEquals(1, clima.size());
    }
    @isTest
        static void climaLlegada(){
            test.startTest();
            StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
            mock.setStaticResource('ClimaMock');
            mock.setStatusCode(200);
            mock.setHeader('Content-Type', 'application/json;charset=UTF-8');

            // Associate the callout with a mock response
            Test.setMock(HttpCalloutMock.class, mock);
            // Call method to test
            
            ClimaRest.getClimaLlegada();
            test.stopTest();

            List<Clima__c> clima = [SELECT Id FROM clima__c WHERE Temperatura__c = 299.71];

            System.assertEquals(1, clima.size());
        }
}